#!/usr/bin/env bash
docker-compose up -d && \
version=$(git describe --tags $(git rev-list --tags --max-count=1))
echo "
===================== 🚀 Done 🚀 ===================

      Created by @LucasApoena
      v.$version
      Access your new links:

      🌎 Pgadmin4: http://localhost:8080

===================== 🚀 Done 🚀 ==================="
